name: Textlint blog and nippo
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.md'
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: Install packages
        run: yarn install
      - name: Fetch base branch
        run: git fetch origin main
      - name: textlint
        run: git diff origin/main HEAD --name-only | grep \.md | xargs yarn textlint
